### ISSUE TITLE
issues on saving files on windows OS 

### ISSUE THREAD

**Issue by Islam-Baraka** [juliandavidmr/sails-inverse-model#14]
Please be aware that there is many issues n saving files on windows platform 

more details 
os: win 7
error on saving messages 

`User       : root
Password   : Not used
Database   : elnga7
Host       : localhost
Models     : C:\Users\Baraka\Desktop\nodejsApps\mvcoutput\models
Views      : C:\Users\Baraka\Desktop\nodejsApps\mvcoutput\views
Controllers: C:\Users\Baraka\Desktop\nodejsApps\mvcoutput\controllers
DB         : mysql
Schema (pg): public
[1 Generating] campaigns table ...
[2 Generating] feedsessions table ...
[3 Generating] localgroups table ...
[4 Generating] locals table ...
[5 Generating] locals_localgroups table ...
[6 Generating] quotes table ...
[7 Generating] scraps table ...
[8 Generating] slaps table ...
[9 Generating] twitterposts table ...
[10 Generating] twitterposts55 table ...
[11 Generating] users table ...
11 tables
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\models'
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\models'
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\models'
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\models'
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\models'
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\models'
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\models'
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\models'
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\models'
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\models'
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\models'
===========
Views [OK]

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\locals'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\locals'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\locals'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\locals'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\users'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\users'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\users'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\twitterposts'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\users'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\twitterposts'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\twitterposts'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\twitterposts'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\localgroups'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\localgroups'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\localsLocalgroups'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\localgroups'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\localgroups'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\localsLocalgroups'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\localsLocalgroups'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\twitterposts55'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\localsLocalgroups'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\twitterposts55'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\twitterposts55'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\feedsessions'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\feedsessions'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\twitterposts55'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\feedsessions'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\feedsessions'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\campaigns'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\campaigns'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\campaigns'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\campaigns'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\quotes'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\quotes'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\quotes'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\quotes'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\scraps'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\scraps'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\scraps'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\scraps'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\slaps'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\slaps'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\slaps'

ERROR
ENOENT: no such file or directory, stat 'C:\Users\Baraka\Desktop\nodejsApps\mvco
utput\views\slaps'

ReferenceError: ansi is not defined
    at gencode.save.then (C:\Users\Baraka\AppData\Roaming\npm\node_modules\sails
-inverse-model\generator\save.js:35:19)
ReferenceError: ansi is not defined
    at gencode.save.then (C:\Users\Baraka\AppData\Roaming\npm\node_modules\sails
-inverse-model\generator\save.js:35:19)
ReferenceError: ansi is not defined
    at gencode.save.then (C:\Users\Baraka\AppData\Roaming\npm\node_modules\sails
-inverse-model\generator\save.js:35:19)
ReferenceError: ansi is not defined
    at gencode.save.then (C:\Users\Baraka\AppData\Roaming\npm\node_modules\sails
-inverse-model\generator\save.js:35:19)
ReferenceError: ansi is not defined
    at gencode.save.then (C:\Users\Baraka\AppData\Roaming\npm\node_modules\sails
-inverse-model\generator\save.js:35:19)
ReferenceError: ansi is not defined
    at gencode.save.then (C:\Users\Baraka\AppData\Roaming\npm\node_modules\sails
-inverse-model\generator\save.js:35:19)
ReferenceError: ansi is not defined
    at gencode.save.then (C:\Users\Baraka\AppData\Roaming\npm\node_modules\sails
-inverse-model\generator\save.js:35:19)
ReferenceError: ansi is not defined
    at gencode.save.then (C:\Users\Baraka\AppData\Roaming\npm\node_modules\sails
-inverse-model\generator\save.js:35:19)
ReferenceError: ansi is not defined
    at gencode.save.then (C:\Users\Baraka\AppData\Roaming\npm\node_modules\sails
-inverse-model\generator\save.js:35:19)
ReferenceError: ansi is not defined
    at gencode.save.then (C:\Users\Baraka\AppData\Roaming\npm\node_modules\sails
-inverse-model\generator\save.js:35:19)
ReferenceError: ansi is not defined
    at gencode.save.then (C:\Users\Baraka\AppData\Roaming\npm\node_modules\sails
-inverse-model\generator\save.js:35:19)

C:\Users\Baraka\Desktop\nodejsApps\mvcoutput>`

ways to solve the issues 
in file : generator / save.js 
changing the mkdir to relative paths 
	mkdir(dir_folder_model).then(() => {
to
	mkdir("Models").then(() => {

and in genviews/views.js 
you may set the folder name to relative path 
var folder_views = "Views";

i will try to have a better solution very soon

**Comment by juliandavidmr** [comment]
Hi @Islam-Baraka , thank you, a pull request will be welcome. 👍  :blush:
